import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Rubik } from "next/font/google";

// Google font import for Rubik
const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--rubik-font",
  style: "normal",
  weight: ["300", "400", "500", "600", "700", "800", "900"]
});

// Local font imports
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--geist-sans-font",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--geist-mono-font",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
